# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
