# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-14 02:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_distrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
                ('apellido', models.CharField(blank=True, max_length=1000, null=True)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=1000, null=True)),
                ('direccion', models.CharField(blank=True, max_length=1000, null=True)),
                ('referencia', models.CharField(blank=True, max_length=1000, null=True)),
                ('texperiencia', models.IntegerField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='static')),
                ('ncuenta', models.CharField(blank=True, max_length=1000, null=True)),
                ('distrito', models.ForeignKey(blank=True, db_column='distrito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Distrito')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socia',
                'db_table': 'socia',
                'managed': True,
            },
        ),
    ]
