# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-14 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_socia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Socia/Especialidad/Opcion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sociasubcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Socia')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Subcategoria')),
            ],
            options={
                'verbose_name': 'Socia/Especialidad',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='opcion',
            name='sociasubcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Sociasubcategoria'),
        ),
    ]
