# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-14 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171114_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='user',
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
